--
-- PostgreSQL database dump
--

\restrict h5CvEhmr51QVFueKRgHtrfUWUDthAvPlsWbBZ1dcHsdnn1EyPManFrn6Bk7hOeB

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Customers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Customers" (
    "Id" integer NOT NULL,
    "FullName" text NOT NULL,
    "Phone" text NOT NULL,
    "Email" text NOT NULL
);


ALTER TABLE public."Customers" OWNER TO postgres;

--
-- Name: Customers_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Customers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Customers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: SalesInvoiceItems; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SalesInvoiceItems" (
    "Id" integer NOT NULL,
    "SalesInvoiceId" integer NOT NULL,
    "VehiclePartId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "UnitPrice" numeric NOT NULL,
    "LineTotal" numeric NOT NULL
);


ALTER TABLE public."SalesInvoiceItems" OWNER TO postgres;

--
-- Name: SalesInvoiceItems_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."SalesInvoiceItems" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SalesInvoiceItems_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: SalesInvoices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SalesInvoices" (
    "Id" integer NOT NULL,
    "CustomerId" integer NOT NULL,
    "InvoiceDate" timestamp with time zone NOT NULL,
    "SubTotal" numeric NOT NULL,
    "DiscountAmount" numeric NOT NULL,
    "GrandTotal" numeric NOT NULL
);


ALTER TABLE public."SalesInvoices" OWNER TO postgres;

--
-- Name: SalesInvoices_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."SalesInvoices" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SalesInvoices_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: VehicleParts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."VehicleParts" (
    "Id" integer NOT NULL,
    "PartName" text NOT NULL,
    "Price" numeric NOT NULL,
    "StockQuantity" integer NOT NULL
);


ALTER TABLE public."VehicleParts" OWNER TO postgres;

--
-- Name: VehicleParts_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."VehicleParts" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."VehicleParts_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Vehicles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Vehicles" (
    "Id" integer NOT NULL,
    "VehicleNumber" text NOT NULL,
    "Brand" text NOT NULL,
    "Model" text NOT NULL,
    "CustomerId" integer NOT NULL
);


ALTER TABLE public."Vehicles" OWNER TO postgres;

--
-- Name: Vehicles_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Vehicles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Vehicles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: Customers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Customers" ("Id", "FullName", "Phone", "Email") FROM stdin;
1	Malisha Test	9800000000	test@mail.com
\.


--
-- Data for Name: SalesInvoiceItems; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."SalesInvoiceItems" ("Id", "SalesInvoiceId", "VehiclePartId", "Quantity", "UnitPrice", "LineTotal") FROM stdin;
1	1	1	2	2000	4000
\.


--
-- Data for Name: SalesInvoices; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."SalesInvoices" ("Id", "CustomerId", "InvoiceDate", "SubTotal", "DiscountAmount", "GrandTotal") FROM stdin;
1	1	2026-04-27 11:59:17.020796+05:45	4000	0	4000
\.


--
-- Data for Name: VehicleParts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."VehicleParts" ("Id", "PartName", "Price", "StockQuantity") FROM stdin;
1	Brake Pad	2000	8
\.


--
-- Data for Name: Vehicles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Vehicles" ("Id", "VehicleNumber", "Brand", "Model", "CustomerId") FROM stdin;
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260427061104_InitialCreate	8.0.0
\.


--
-- Name: Customers_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Customers_Id_seq"', 1, true);


--
-- Name: SalesInvoiceItems_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."SalesInvoiceItems_Id_seq"', 1, true);


--
-- Name: SalesInvoices_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."SalesInvoices_Id_seq"', 1, true);


--
-- Name: VehicleParts_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."VehicleParts_Id_seq"', 1, true);


--
-- Name: Vehicles_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Vehicles_Id_seq"', 1, false);


--
-- Name: Customers PK_Customers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Customers"
    ADD CONSTRAINT "PK_Customers" PRIMARY KEY ("Id");


--
-- Name: SalesInvoiceItems PK_SalesInvoiceItems; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SalesInvoiceItems"
    ADD CONSTRAINT "PK_SalesInvoiceItems" PRIMARY KEY ("Id");


--
-- Name: SalesInvoices PK_SalesInvoices; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SalesInvoices"
    ADD CONSTRAINT "PK_SalesInvoices" PRIMARY KEY ("Id");


--
-- Name: VehicleParts PK_VehicleParts; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."VehicleParts"
    ADD CONSTRAINT "PK_VehicleParts" PRIMARY KEY ("Id");


--
-- Name: Vehicles PK_Vehicles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Vehicles"
    ADD CONSTRAINT "PK_Vehicles" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_SalesInvoiceItems_SalesInvoiceId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_SalesInvoiceItems_SalesInvoiceId" ON public."SalesInvoiceItems" USING btree ("SalesInvoiceId");


--
-- Name: IX_SalesInvoiceItems_VehiclePartId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_SalesInvoiceItems_VehiclePartId" ON public."SalesInvoiceItems" USING btree ("VehiclePartId");


--
-- Name: IX_SalesInvoices_CustomerId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_SalesInvoices_CustomerId" ON public."SalesInvoices" USING btree ("CustomerId");


--
-- Name: IX_Vehicles_CustomerId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Vehicles_CustomerId" ON public."Vehicles" USING btree ("CustomerId");


--
-- Name: SalesInvoiceItems FK_SalesInvoiceItems_SalesInvoices_SalesInvoiceId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SalesInvoiceItems"
    ADD CONSTRAINT "FK_SalesInvoiceItems_SalesInvoices_SalesInvoiceId" FOREIGN KEY ("SalesInvoiceId") REFERENCES public."SalesInvoices"("Id") ON DELETE CASCADE;


--
-- Name: SalesInvoiceItems FK_SalesInvoiceItems_VehicleParts_VehiclePartId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SalesInvoiceItems"
    ADD CONSTRAINT "FK_SalesInvoiceItems_VehicleParts_VehiclePartId" FOREIGN KEY ("VehiclePartId") REFERENCES public."VehicleParts"("Id") ON DELETE CASCADE;


--
-- Name: SalesInvoices FK_SalesInvoices_Customers_CustomerId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SalesInvoices"
    ADD CONSTRAINT "FK_SalesInvoices_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES public."Customers"("Id") ON DELETE CASCADE;


--
-- Name: Vehicles FK_Vehicles_Customers_CustomerId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Vehicles"
    ADD CONSTRAINT "FK_Vehicles_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES public."Customers"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict h5CvEhmr51QVFueKRgHtrfUWUDthAvPlsWbBZ1dcHsdnn1EyPManFrn6Bk7hOeB

